name       : qmapshack
version    : 1.14.0
release    : 8
source     :
    - https://github.com/Maproom/qmapshack/archive/V_1.14.0.tar.gz : fd50f335b741087ab228ce4f8f45e386562eb128aea84298a1bdcfd299126576
license    : GPL-3.0-or-later
component  : desktop
summary    : GPS mapping and management tool
description: |
    Use QMapShack to plan your next outdoor trip or to visualize and archive all the GPS recordings of your past exciting adventures. QMapShack is the next generation of the famous QLandkarte GT application. And of course it's even better and easier to use.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(gdal)
    - pkgconfig(libturbojpeg)
    - pkgconfig(proj)
    - alglib
    - quazip-devel
    - routino-devel
setup      : |
    %apply_patches
    install -Dm00644 $pkgfiles/line_3px_horizontal.png $workdir/src/qmaptool/pic/line_3px_horizontal.png
    install -Dm00644 $pkgfiles/line_3px_vertical.png $workdir/src/qmaptool/pic/line_3px_vertical.png
    install -Dm00644 $pkgfiles/splash.png $workdir/src/qmaptool/pic/splash.png
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
