name       : qmapshack
version    : 1.11.1
release    : 1
source     :
    - https://bitbucket.org/maproom/qmapshack/downloads/qmapshack-1.11.1.tar.gz : 3e65e443665041bb4c10ebd10fb49ca6df9015d9cecd2551a888bbdaa8a3117b
license    : GPL-3.0-or-later
component  : desktop
summary    : GPS mapping and management tool
description: |
    Use QMapShack to plan your next outdoor trip or to visualize and archive all the GPS recordings of your past exciting adventures. QMapShack is the next generation of the famous QLandkarte GT application. And of course it's even better and easier to use.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(gdal)
    - pkgconfig(libturbojpeg)
    - pkgconfig(proj)
    - alglib
    - quazip-devel
    - routino-devel
setup      : |
    %patch -p1 < $pkgfiles/qmapshack-qaction.patch

    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
